// auth
export const RESET_LOGINPWD = 'RESET_LOGINPWD'
export const RESET_DEALPWD = 'RESET_DEALPWD'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_TOKEN = 'SET_TOKEN'
export const GET_TOKEN = 'GET_TOKEN'
export const GET_USERINFO = 'GET_USERINFO'
export const SET_OPENID = 'SET_OPENID'
export const GET_OPENID = 'GET_OPENID'
export const REMOVE_ALL_STORAGE = 'REMOVE_ALL_STORAGE'
export const FORGET_DEALPWD = 'REMOVE_ALL_STORAGE'
// global
export const GET_INDEX_IMAGES = 'GET_INDEX_IMAGES'
export const GET_HOME_INFO = 'GET_HOME_INFO'
// products
export const GET_DORAEMON_LIST = 'GET_DORAEMON_LIST'
export const SET_MONTH_DETAIL = 'SET_MONTH_DETAIL'
export const SET_YEAR_DETAIL = 'SET_YEAR_DETAIL'
export const SET_MONTHPROFIT_DETAIL = 'SET_MONTHPROFIT_DETAIL'
export const GET_MONTHPROFIT_LIST = 'GET_MONTHPROFIT_LIST'
export const SET_MONTHPROFIT_CURRENTPAGE = 'SET_MONTHPROFIT_CURRENTPAGE'
// pay
export const BANLANCE_PAY = 'BANLANCE_PAY'
export const BANK_PAY_PARAMS = 'BANK_PAY_PARAMS'
export const PROFIT_INVEST = 'PROFIT_INVEST'

export const GET_CODE = 'GET_CODE'
