export const RESET_LOGINPWD = 'RESET_LOGINPWD'
export const RESET_DEALPWD = 'RESET_DEALPWD'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_TOKEN = 'SET_TOKEN'
export const GET_TOKEN = 'GET_TOKEN'
export const GET_USERINFO = 'GET_USERINFO'
